stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/thyroid.csv
    outs:
    - data/raw/dataset.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/dataset.csv
    outs:
    - data/processed/test_dataset.csv
    - data/processed/train_dataset.csv
  
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - src/train_and_evaluate.py
    - data/processed/test_dataset.csv
    - data/processed/train_dataset.csv
    params:
    - estimators.RandomForestClassifier.params.n_estimators
    - estimators.RandomForestClassifier.params.min_samples_split
    - estimators.RandomForestClassifier.params.max_features
    - estimators.RandomForestClassifier.params.criterion
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false

    outs: 
    - models/model.joblib