base:
  project: thyroid-detection
  random_state: 42
  target_col: class

data_source:
    s3_source: data_given/thyroid.csv

load_data:
  raw_dataset_csv: data/raw/dataset.csv

split_data:
  train_path: data/processed/train_dataset.csv
  test_path: data/processed/test_dataset.csv

estimators:
  RandomForestClassifier:
    params:
      criterion: "gini"
      max_features: "sqrt"
      min_samples_split: 5
      n_estimators: 200

reports:
  params: reports/params.json
  scores: reports/scores.json

model_dir: models